config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :notes
  end
  resources :reports, only: [:index]
  root to: "reports#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  scope :with_date, -> (date) { where(date: date.beginning_of_day..date.end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_user
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = @user.notes
  end

  def show
  end

  def new
    date = params[:date] ? Date.parse(params[:date]) : Date.now
    @note = @user.notes.new(date: date)
  end

  def edit
  end

  def create
    @note = @user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to root_path(date: @note.date), notice: 'Note was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to root_path(date: @note.date), notice: 'Note was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to user_notes_url(@user), notice: 'Note was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_note
      def set_user
        @user = User.find(params[:user_id])
      end
      @note = @user.notes.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:date, :content)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_date

  def index
    @users = User.all # TODO: 報告対象者だけに絞る
  end

  private
    def set_date
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def indent(text, level = 1, count = 2)
    spaces = ' ' * count * level
    text.each_line.map {|line| line.chomp.empty? ? line : spaces + line }.join
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      = current_user.name
      %span.caret
    %ul.dropdown-menu
      %li= link_to 'マイページ', '#'
      %li= link_to '設定', edit_user_registration_path
      %li.divider
      %li= link_to 'ログアウト', destroy_user_session_path, method: :delete
- else
  %li= link_to 'サインアップ', new_user_registration_path
  %li= link_to 'ログイン', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Morning'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Morning'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/notes/_form.html.haml
%h1= l @note.date, format: :long

= simple_form_for [@user, @note] do |f|
  = f.input :date, as: :hidden
  = f.input :content, as: :text, input_html: {rows: 10}
  = f.button :submit

= link_to 'Back', root_path(date: @note.date)

app/views/notes/edit.html.haml
= render 'form'

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %thead
    %tr
      %th Date
      %th Content
      %th User
      %th
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= note.date
        %td= note.content
        %td= note.user.name
        %td= link_to 'Show', [@user, note]
        %td= link_to 'Edit', edit_user_note_path(@user, note)
        %td= link_to 'Destroy', [@user, note], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Note', new_user_note_path(@user)

app/views/notes/new.html.haml
= render 'form'

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @note.date
%p
  %b Content:
  = @note.content
%p
  %b User:
  = @note.user.name

= link_to 'Edit', edit_user_note_path(@user, @note)
\|
= link_to 'Back', user_notes_path

app/views/reports/index.html.haml
.report_title
  %p.report_title_item= link_to '<<' ,root_path(date: @date.yesterday.strftime("%Y-%m-%d"))
  %h1.report_title_item= l @date, format: :long
  %p.report_title_item= link_to '>>' ,root_path(date: @date.tomorrow.strftime("%Y-%m-%d"))

=link_to "メール送信用フォーマット", reports_path(:format => :text, date: @date)
- @users.each do |user|
  .note
    .note-title
      %h2.note-author= user.name
      - note = user.notes.with_date(@date).first
      = link_to fa_icon('edit', text: '編集'), note ? edit_user_note_path(user, note) : new_user_note_path(user, date: @date.strftime("%Y-%m-%d")), class: 'note-edit-link'
    .note-content
      - if note
        = simple_format note.content

app/views/reports/index.text.erb
<%= l @date, format: :long %>

<% @users.each do |user| %>
<%= user.name %>
<% note = user.notes.with_date(@date).first %>
<% if note %>
<%= indent(note.content, 1) %>

<% end %>
<% end %>